import path from 'path';

/**
 * Allowed file extensions for document processing
 */
const ALLOWED_EXTENSIONS = ['.pdf', '.docx', '.txt', '.md'];

/**
 * Maximum file size in bytes (100MB)
 */
const MAX_FILE_SIZE = 100 * 1024 * 1024;

/**
 * Maximum message length in characters
 */
const MAX_MESSAGE_LENGTH = 10000;

/**
 * Validation result interface
 */
export interface ValidationResult {
  valid: boolean;
  error?: string;
}

/**
 * Validates a file path for document processing
 * Checks for:
 * - Absolute path
 * - Allowed file extension
 * - Path traversal attempts
 */
export function validateFilePath(filePath: string): ValidationResult {
  // Check if filePath is provided and is a string
  if (!filePath || typeof filePath !== 'string') {
    return { valid: false, error: 'File path must be a non-empty string' };
  }

  // Trim whitespace
  const trimmedPath = filePath.trim();

  // Check if path is absolute
  if (!path.isAbsolute(trimmedPath)) {
    return { valid: false, error: 'File path must be absolute' };
  }

  // Normalize the path to resolve any . or .. segments
  const normalizedPath = path.normalize(trimmedPath);

  // Check for path traversal attempts
  // Reject paths containing '..' to prevent directory traversal attacks
  if (trimmedPath.includes('..')) {
    return { valid: false, error: 'Path traversal is not allowed' };
  }

  // Reject if normalized path differs from original (indicates suspicious path manipulation)
  if (normalizedPath !== trimmedPath.replace(/\\/g, path.sep)) {
    return { valid: false, error: 'Invalid path format' };
  }

  // Check extension
  const ext = path.extname(normalizedPath).toLowerCase();
  if (!ALLOWED_EXTENSIONS.includes(ext)) {
    return {
      valid: false,
      error: `Invalid file extension: ${ext}. Allowed extensions: ${ALLOWED_EXTENSIONS.join(', ')}`
    };
  }

  return { valid: true };
}

/**
 * Validates message content for chat
 * Checks for:
 * - Non-empty string
 * - Maximum length
 */
export function validateMessageContent(message: string): ValidationResult {
  if (!message || typeof message !== 'string') {
    return { valid: false, error: 'Message must be a non-empty string' };
  }

  const trimmedMessage = message.trim();

  if (trimmedMessage.length === 0) {
    return { valid: false, error: 'Message cannot be empty' };
  }

  if (trimmedMessage.length > MAX_MESSAGE_LENGTH) {
    return {
      valid: false,
      error: `Message exceeds maximum length of ${MAX_MESSAGE_LENGTH} characters`
    };
  }

  return { valid: true };
}

/**
 * Validates a document ID
 * Document IDs should be UUIDs (generated by uuid library)
 * Format: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
 */
export function validateDocumentId(documentId: string): ValidationResult {
  if (!documentId || typeof documentId !== 'string') {
    return { valid: false, error: 'Document ID must be a non-empty string' };
  }

  // UUID v4 regex pattern
  const uuidPattern = /^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;

  if (!uuidPattern.test(documentId)) {
    return { valid: false, error: 'Document ID must be a valid UUID' };
  }

  return { valid: true };
}

/**
 * Sanitizes a document ID for use in queries
 * Only allows alphanumeric characters and hyphens
 * Returns null if the ID contains invalid characters
 */
export function sanitizeDocumentId(documentId: string): string | null {
  if (!documentId || typeof documentId !== 'string') {
    return null;
  }

  // Only allow alphanumeric characters and hyphens (UUID format)
  const sanitized = documentId.replace(/[^a-zA-Z0-9-]/g, '');

  // If sanitization changed the string, the original was invalid
  if (sanitized !== documentId) {
    return null;
  }

  return sanitized;
}
