/**
 * Nederlandse voornamen en achternamen
 *
 * Bronnen: CBS/SVB meest voorkomende namen in Nederland.
 * Dit is een subset van de meest gangbare namen voor effectieve detectie
 * zonder te veel false positives.
 */

export const DUTCH_FIRST_NAMES: string[] = [
  // Mannelijke voornamen (top 200+)
  'Aaron', 'Abel', 'Adam', 'Adrian', 'Albert', 'Alex', 'Alexander', 'Ali',
  'Amos', 'André', 'Andreas', 'Andries', 'Anton', 'Arie', 'Arjan', 'Arjen',
  'Arnold', 'Arthur', 'Bas', 'Bastiaan', 'Ben', 'Benjamin', 'Bert', 'Boris',
  'Bram', 'Brian', 'Bruno', 'Casper', 'Chris', 'Christiaan', 'Christian',
  'Cornelis', 'Daan', 'Daniël', 'Danny', 'Dave', 'David', 'Dennis', 'Derk',
  'Diederik', 'Diederick', 'Dirk', 'Dylan', 'Eduard', 'Edwin', 'Emiel',
  'Erwin', 'Evert', 'Fabian', 'Ferdinand', 'Florian', 'Floris', 'Frank',
  'Frans', 'Fred', 'Frederik', 'Freek', 'Gerrit', 'Gert', 'Gijs', 'Guido',
  'Guus', 'Hans', 'Harm', 'Harold', 'Harrie', 'Harry', 'Hendrik', 'Henk',
  'Henri', 'Herman', 'Hugo', 'Ibrahim', 'Ivo', 'Jaap', 'Jack', 'Jacob',
  'Jacques', 'Jan', 'Jandirk', 'Jasper', 'Jeffrey', 'Jelmer', 'Jeroen',
  'Jesse', 'Jim', 'Job', 'Jochem', 'Johan', 'Johannes', 'John', 'Jonathan',
  'Joost', 'Joop', 'Joris', 'Jos', 'Joshua', 'Jurgen', 'Justin', 'Karel',
  'Kees', 'Kevin', 'Klaas', 'Lars', 'Laurens', 'Leo', 'Leon', 'Levi',
  'Liam', 'Lukas', 'Maarten', 'Marc', 'Marcel', 'Marco', 'Marijn', 'Mark',
  'Martin', 'Martijn', 'Mathijs', 'Matthijs', 'Maurits', 'Max', 'Michiel',
  'Michel', 'Mike', 'Mohammed', 'Niels', 'Nick', 'Nico', 'Noah', 'Noud',
  'Olivier', 'Oscar', 'Otto', 'Pascal', 'Patrick', 'Paul', 'Peter', 'Piet',
  'Pieter', 'Quinten', 'Ralf', 'Ramon', 'Remco', 'René', 'Richard', 'Rick',
  'Rob', 'Robert', 'Robin', 'Robbert', 'Rogier', 'Roland', 'Ron', 'Ronald',
  'Ruben', 'Ruud', 'Rutger', 'Sam', 'Sander', 'Sebastiaan', 'Sem', 'Simon',
  'Stan', 'Stefan', 'Stephan', 'Stijn', 'Sven', 'Teun', 'Theo', 'Thijs',
  'Thomas', 'Tijn', 'Tim', 'Tom', 'Victor', 'Vincent', 'Wijnand', 'Wil',
  'Willem', 'Wim', 'Wouter', 'Youssef',

  // Vrouwelijke voornamen (top 200+)
  'Amber', 'Amy', 'Andrea', 'Angela', 'Angelique', 'Anita', 'Anja', 'Anke',
  'Anna', 'Anne', 'Annelies', 'Annemarie', 'Annet', 'Annette', 'Annie',
  'Anouk', 'Astrid', 'Barbara', 'Bianca', 'Bo', 'Brigitte', 'Carlijn',
  'Carmen', 'Caroline', 'Chantal', 'Charlotte', 'Claudia', 'Corina',
  'Cornelia', 'Daphne', 'Denise', 'Diana', 'Diane', 'Dominique', 'Dora',
  'Edith', 'Eline', 'Elisa', 'Elisabeth', 'Elise', 'Ellen', 'Els',
  'Esther', 'Eva', 'Evelien', 'Femke', 'Fleur', 'Floor', 'Gerda',
  'Greta', 'Grietje', 'Hanna', 'Hanneke', 'Heleen', 'Helma', 'Hendrika',
  'Henriette', 'Ilse', 'Ingrid', 'Irene', 'Iris', 'Isabel', 'Jacqueline',
  'Jana', 'Janine', 'Janneke', 'Jennifer', 'Jessica', 'Jolanda', 'Julia',
  'Karen', 'Karin', 'Karlijn', 'Katja', 'Kim', 'Laura', 'Leontien',
  'Lies', 'Liesbeth', 'Linda', 'Lisa', 'Lisanne', 'Loes', 'Lotte',
  'Louise', 'Maaike', 'Manon', 'Marga', 'Margriet', 'Maria', 'Marianne',
  'Marie', 'Marieke', 'Marije', 'Marijke', 'Marina', 'Mariska', 'Marjan',
  'Marloes', 'Martine', 'Melissa', 'Michelle', 'Mieke', 'Miriam', 'Monique',
  'Nadia', 'Naomi', 'Nathalie', 'Nicolette', 'Nicole', 'Nina', 'Nora',
  'Patricia', 'Paula', 'Pauline', 'Petra', 'Rachel', 'Rebecca', 'Regina',
  'Renate', 'Renske', 'Rianne', 'Rosalie', 'Sandra', 'Sanne', 'Sara',
  'Sarah', 'Saskia', 'Silvia', 'Simone', 'Sophie', 'Suzanne', 'Sylvia',
  'Tamara', 'Tanja', 'Thea', 'Wendy', 'Wilma', 'Yvonne',
];

export const DUTCH_LAST_NAMES: string[] = [
  // Meest voorkomende achternamen in Nederland (top 300+)
  'Aalbers', 'Aarts', 'Adriaansen', 'Akker', 'Alblas',
  'Baan', 'Baas', 'Bakker', 'Bal', 'Barends', 'Bauer', 'Beek', 'Beer',
  'Berg', 'Bergen', 'Berger', 'Bergman', 'Beukers', 'Bijl', 'Blaauw',
  'Blok', 'Bloem', 'Boer', 'Boogaard', 'Boom', 'Boon', 'Boor', 'Bos',
  'Bosch', 'Bosma', 'Bouwman', 'Bouwmeester', 'Braam', 'Brand', 'Brands',
  'Breeuwer', 'Brink', 'Brinkman', 'Broek', 'Broekhuizen', 'Brouwer',
  'Bruijn', 'Bruijne', 'Bruin', 'Bruins', 'Buijs', 'Buis', 'Burger',
  'Bussche', 'Buuren',
  'Cohen', 'Coolen', 'Cornelissen', 'Coster',
  'Daal', 'Dam', 'Dekker', 'Dijk', 'Dijkema', 'Dijkman', 'Dijkstra',
  'Donk', 'Donker', 'Doorn', 'Driessen', 'Duin', 'Duijn',
  'Eijk', 'Eijkel', 'Eijkman', 'Elders', 'Engel', 'Evers',
  'Faber', 'Flink', 'Fontein', 'Franken', 'Franssen',
  'Geerlings', 'Geerts', 'Gerritsen', 'Gielen', 'Goedhart', 'Goud',
  'Graaf', 'Groen', 'Groenendaal', 'Groenewold', 'Groot', 'Gulden',
  'Haag', 'Haas', 'Hagen', 'Hakker', 'Harmsen', 'Hart', 'Haver',
  'Heemskerk', 'Heerma', 'Heijden', 'Hendriks', 'Hengst', 'Hermans',
  'Heuvel', 'Hoek', 'Hoekstra', 'Hoffman', 'Hofman', 'Hofstede',
  'Holleman', 'Holt', 'Hoogeveen', 'Hoogendoorn', 'Horst', 'Houben',
  'Huisman', 'Huizen',
  'Jacobs', 'Jager', 'Jan', 'Jansen', 'Janssen', 'Janssens', 'Jong',
  'Jonge', 'Jongen', 'Jonker', 'Joosten',
  'Kamp', 'Kampen', 'Kant', 'Kappers', 'Karsten', 'Kerk', 'Kerkhof',
  'Keulen', 'Klein', 'Kleijn', 'Kling', 'Klok', 'Knaap', 'Knol',
  'Koek', 'Koeman', 'Kok', 'Koning', 'Kool', 'Koopman', 'Koopmans',
  'Koot', 'Korte', 'Koster', 'Kraai', 'Kramer', 'Kroon', 'Kuijper',
  'Kuijpers', 'Kuiper', 'Kuipers',
  'Laan', 'Laar', 'Laarhoven', 'Lam', 'Lange', 'Leemans', 'Leeuw',
  'Linden', 'Lingen', 'Looij', 'Loon', 'Lucassen',
  'Maas', 'Maassen', 'Maat', 'Mans', 'Meer', 'Meijer', 'Meijers',
  'Meulen', 'Meyer', 'Molenaar', 'Mol', 'Molen', 'Mulder', 'Muller',
  'Nagelkerke', 'Nauta', 'Nieuwenhuis', 'Nijhof', 'Nijhuis', 'Nijland',
  'Nobel', 'Nooij', 'Noort', 'Norden',
  'Oerlemans', 'Oomen', 'Oord', 'Oorschot', 'Oort', 'Otten', 'Oudshoorn',
  'Pas', 'Peters', 'Petersen', 'Pieters', 'Pietersen', 'Plasman', 'Poel',
  'Pol', 'Post', 'Postma', 'Prins', 'Pronk',
  'Raad', 'Raven', 'Reijnen', 'Riet', 'Rijke', 'Rijn', 'Rijnders',
  'Rijswijk', 'Roelofs', 'Roos', 'Rosenberg', 'Ruiter', 'Rutten',
  'Schaaf', 'Schaap', 'Schenk', 'Schilder', 'Schipper', 'Schmid',
  'Schmidt', 'Schneider', 'Schoenmaker', 'Scholten', 'Schouten', 'Schreuder',
  'Schulte', 'Siebelink', 'Sloot', 'Sluiter', 'Smeets', 'Smid', 'Smit',
  'Smits', 'Snijder', 'Snijders', 'Steen', 'Steenbergen', 'Stolk',
  'Stout', 'Strijbos', 'Struijk', 'Stuij', 'Swart',
  'Terpstra', 'Timmerman', 'Timmermans', 'Toorn',
  'Vaart', 'Valk', 'Veenstra', 'Veld', 'Velde', 'Velden', 'Ven',
  'Verbeek', 'Verhoef', 'Verhoeven', 'Vermeer', 'Vermeulen', 'Verschoor',
  'Verschuren', 'Visser', 'Vliet', 'Vogel', 'Vonk', 'Voorn', 'Vos',
  'Vries', 'Vrij', 'Vugt', 'Vuuren',
  'Waal', 'Wagenaar', 'Wal', 'Weerden', 'Weg', 'Wester', 'Westerhof',
  'Westerink', 'Westra', 'Willems', 'Willemsen', 'Wit', 'Wolff', 'Wolters',
  'Woud', 'Woude',
  'Zaal', 'Zanden', 'Zandstra', 'Zee', 'Zeeman', 'Zijl', 'Zijlstra',
  'Zoet', 'Zwaan', 'Zwart',
];

/**
 * Tussenvoegels die voorkomen in Nederlandse achternamen
 */
export const DUTCH_PREFIXES: string[] = [
  'de', 'den', 'der', 'des',
  'het', "'t",
  'van', 'van de', 'van den', 'van der', 'van het', "van 't",
  'in', 'in de', 'in den', "in 't",
  'op', 'op de', 'op den', 'op het', "op 't",
  'te', 'ten', 'ter',
  'tot',
  'uit', 'uit de', 'uit den', 'uit het', "uit 't",
  'aan', 'aan de', 'aan den', 'aan het', "aan 't",
  'bij', 'bij de', 'bij den', 'bij het', "bij 't",
  'onder', 'onder de', 'onder den', 'onder het',
  'over', 'over de', 'over den', 'over het',
  'voor', 'voor de', 'voor den', 'voor het',
];

/**
 * Aanspreekvormen die aangeven dat een naam volgt
 */
export const NAME_INDICATORS: string[] = [
  'Dhr.', 'Dhr', 'Mevr.', 'Mevr', 'Mw.', 'Mw',
  'de heer', 'mevrouw', 'meneer',
  'Dr.', 'Dr', 'Prof.', 'Prof', 'Mr.', 'Mr', 'Ir.', 'Ir',
  'Ing.', 'Ing', 'Ds.', 'Ds',
  'Naam:', 'naam:', 'Name:', 'name:',
  'Geachte', 'Beste',
  'geb.', 'geboren',
  'namens', 'ondertekend door', 'ondertekend',
  't.a.v.', 'ter attentie van', 'T.a.v.',
  'contactpersoon', 'Contactpersoon',
  'behandelaar', 'Behandelaar',
  'patiënt', 'Patiënt', 'patient', 'Patient',
  'cliënt', 'Cliënt', 'client', 'Client',
  'bewoner', 'Bewoner',
  'verzekerde', 'Verzekerde',
];
