/**
 * Nederlandse voornamen en achternamen
 *
 * Bronnen: CBS/SVB meest voorkomende namen in Nederland.
 * Dit is een subset van de meest gangbare namen voor effectieve detectie
 * zonder te veel false positives.
 */

export const DUTCH_FIRST_NAMES: string[] = [
  // Mannelijke voornamen (top 200+ Dutch + immigrant names)
  'Aaron', 'Abel', 'Abdelkarim', 'Abdellatif', 'Adam', 'Adrian', 'Ahmed', 'Ahmet',
  'Albert', 'Alex', 'Alexander', 'Ali', 'Amos', 'André', 'Andreas', 'Andries',
  'Andrzej', 'Anton', 'Arie', 'Arjan', 'Arjen', 'Arnold', 'Arthur', 'Axel',
  'Bas', 'Bastiaan', 'Ben', 'Benjamin', 'Bert', 'Boris', 'Bram', 'Brian', 'Bruno',
  'Casper', 'Cem', 'Chris', 'Christiaan', 'Christian', 'Cornelis',
  'Daan', 'Daniël', 'Danny', 'Dave', 'David', 'Dennis', 'Derk', 'Diederik',
  'Diederick', 'Dirk', 'Dries', 'Dylan',
  'Eduard', 'Edwin', 'Emiel', 'Emre', 'Erkan', 'Erwin', 'Evert',
  'Fabian', 'Fatih', 'Ferdinand', 'Finn', 'Florian', 'Floris', 'Frank', 'Frans',
  'Fred', 'Frederik', 'Freek',
  'Geert', 'Gerrit', 'Gert', 'Giel', 'Gijs', 'Guido', 'Guus',
  'Halil', 'Hamza', 'Hans', 'Harm', 'Harold', 'Harrie', 'Harry', 'Hasan', 'Hassan',
  'Hendrik', 'Henk', 'Henri', 'Herman', 'Hicham', 'Hugo',
  'Ibrahim', 'Ismail', 'Ivo', 'Jaap', 'Jac', 'Jack', 'Jacek', 'Jacob', 'Jacques',
  'Jalal', 'Jamal', 'Jan', 'Jandirk', 'Jane', 'Janusz', 'Jasper', 'Jean', 'Jeffrey',
  'Jelle', 'Jelmer', 'Jeroen', 'Jesse', 'Jim', 'Job', 'Jochem', 'Johan', 'Johannes',
  'John', 'Jonathan', 'Joost', 'Joop', 'Joppe', 'Jordi', 'Joris', 'Jorn', 'Jos',
  'Joshua', 'Jozef', 'Jurgen', 'Justin',
  'Kacper', 'Kadir', 'Karel', 'Karim', 'Kas', 'Kasper', 'Kees', 'Kerem', 'Kevin',
  'Khalid', 'Klaas', 'Koen', 'Krzysztof',
  'Lars', 'Lasse', 'Laurens', 'Leo', 'Leon', 'Levi', 'Liam', 'Luc', 'Luca', 'Lucas',
  'Lukas',
  'Maarten', 'Marc', 'Marcel', 'Marco', 'Marijn', 'Mark', 'Marten', 'Martin',
  'Martijn', 'Mathijs', 'Matthijs', 'Maurits', 'Max', 'Mees', 'Mehmet', 'Michiel',
  'Michel', 'Mike', 'Milan', 'Mirosław', 'Mohammed', 'Murat', 'Mustafa',
  'Niels', 'Nick', 'Nico', 'Noah', 'Nood', 'Noor', 'Noud',
  'Olivier', 'Omar', 'Oscar', 'Osman', 'Otto',
  'Pascal', 'Patrick', 'Paul', 'Peter', 'Piet', 'Pieter', 'Pim', 'Piotr',
  'Quinten',
  'Raf', 'Ralf', 'Ramon', 'Recep', 'Remco', 'René', 'Rens', 'Richard', 'Rick',
  'Rik', 'Rob', 'Robert', 'Robin', 'Robbert', 'Rogier', 'Roland', 'Ron', 'Ronald',
  'Ruben', 'Ruud', 'Rutger',
  'Salim', 'Samir', 'Sam', 'Sander', 'Sebastiaan', 'Selim', 'Sem', 'Serkan', 'Simon',
  'Stan', 'Stanisław', 'Stefan', 'Stef', 'Stephan', 'Stijn', 'Sven',
  'Tariq', 'Teun', 'Thibault', 'Theo', 'Thijs', 'Thomas', 'Ties', 'Tijn', 'Tim',
  'Timo', 'Tom', 'Toon',
  'Victor', 'Vincent',
  'Wijnand', 'Wil', 'Willem', 'Wim', 'Wojciech', 'Wouter',
  'Yannick', 'Youssef', 'Yusuf',
  'Zbigniew',

  // Vrouwelijke voornamen (top 200+ Dutch + immigrant names)
  'Agnes', 'Agnieszka', 'Aisha', 'Aleksandra', 'Alicja', 'Alima', 'Amber', 'Amelia',
  'Amina', 'Amira', 'Amy', 'Andrea', 'Angela', 'Angelique', 'Anita', 'Anja', 'Anke',
  'Anna', 'Anne', 'Annelies', 'Annemarie', 'Annet', 'Annette', 'Annie', 'Anouk',
  'Assia', 'Astrid', 'Ayşe',
  'Badra', 'Barbara', 'Beata', 'Bente', 'Bianca', 'Bo', 'Brigitte',
  'Carlijn', 'Carmen', 'Caroline', 'Chantal', 'Charlotte', 'Christa', 'Claudia',
  'Colette', 'Corina', 'Cornelia',
  'Daphne', 'Darifa', 'Denise', 'Diana', 'Diane', 'Dina', 'Dominique', 'Dora',
  'Dounia',
  'Ebru', 'Edith', 'Eline', 'Elisa', 'Elisabeth', 'Elise', 'Elize', 'Ellen', 'Els',
  'Emine', 'Emma', 'Emmy', 'Esther', 'Eva', 'Evelien',
  'Fadela', 'Farida', 'Fatima', 'Femke', 'Fenne', 'Fieke', 'Fienke', 'Fleur',
  'Floor',
  'Gerda', 'Greta', 'Grietje',
  'Hanna', 'Hanneke', 'Heleen', 'Helma', 'Hendrika', 'Henriette',
  'Ilse', 'Ingrid', 'Irene', 'Iris', 'Isa', 'Isabel',
  'Jacqueline', 'Jana', 'Janine', 'Janneke', 'Jennifer', 'Jessica', 'Jolanda', 'Julia',
  'Karen', 'Karin', 'Karlijn', 'Katarzyna', 'Katja', 'Kim',
  'Lara', 'Laura', 'Lena', 'Leontien', 'Leyla', 'Lies', 'Liesbeth', 'Linda', 'Lisa',
  'Lisanne', 'Loes', 'Lore', 'Lotte', 'Louise',
  'Maaike', 'Magdalena', 'Manon', 'Marga', 'Margriet', 'Maria', 'Marianne', 'Marie',
  'Marieke', 'Marije', 'Marijke', 'Marina', 'Mariska', 'Marjan', 'Marlies', 'Marloes',
  'Martine', 'Melissa', 'Merve', 'Michelle', 'Mieke', 'Mila', 'Miriam', 'Monique',
  'Nadia', 'Naomi', 'Nathalie', 'Nilay', 'Nicolette', 'Nicole', 'Nienke', 'Nina',
  'Noor', 'Nora', 'Nur',
  'Olivia',
  'Patricia', 'Paula', 'Pauline', 'Pelin', 'Petra',
  'Rachel', 'Rebecca', 'Regina', 'Renate', 'Renée', 'Renske', 'Rianne', 'Romy',
  'Roos', 'Rosalie',
  'Sandra', 'Sanne', 'Sara', 'Sarah', 'Saskia', 'Sedef', 'Selin', 'Serap', 'Sibel',
  'Silke', 'Silvia', 'Simone', 'Sophie', 'Suzanne', 'Sylvia',
  'Tamara', 'Tanja', 'Tess', 'Thea', 'Tulay',
  'Veerle',
  'Wendy', 'Wilma',
  'Yasmine', 'Yvonne',
  'Zeynep', 'Zoë',
];

export const DUTCH_LAST_NAMES: string[] = [
  // Meest voorkomende achternamen in Nederland (top 300+)
  'Aalbers', 'Aarts', 'Adriaansen', 'Akker', 'Alblas', 'Amrani', 'Angelo',
  'Baan', 'Baas', 'Bakker', 'Bal', 'Barends', 'Bauer', 'Beek', 'Beer',
  'Berg', 'Bergen', 'Berger', 'Bergman', 'Beukers', 'Bijl', 'Blaauw',
  'Blok', 'Bloem', 'Boer', 'Boogaard', 'Boom', 'Boon', 'Boor', 'Bos',
  'Bosch', 'Bosma', 'Bouwman', 'Bouwmeester', 'Braam', 'Brand', 'Brands',
  'Breeuwer', 'Brink', 'Brinkman', 'Broek', 'Broekhuizen', 'Brouwer',
  'Bruijn', 'Bruijne', 'Bruin', 'Bruins', 'Buijs', 'Buis', 'Burger', 'Burgler',
  'Bussche', 'Buuren',
  'Celik', 'Çelik', 'Cohen', 'Coolen', 'Cornelissen', 'Coster',
  'Daal', 'Dam', 'Damme', 'Dekker', 'Dijk', 'Dijkema', 'Dijkman', 'Dijkstra',
  'Donk', 'Donker', 'Doorn', 'Driessen', 'Duin', 'Duijn',
  'Eijk', 'Eijkel', 'Eijkman', 'Elders', 'Engel', 'Evers',
  'Faber', 'Flink', 'Fontein', 'Franken', 'Franssen',
  'Geerlings', 'Geerts', 'Gerritsen', 'Gielen', 'Goedhart', 'Goud',
  'Graaf', 'Groen', 'Groenendaal', 'Groenewold', 'Groot', 'Gulden',
  'Haag', 'Haas', 'Hagen', 'Hakker', 'Harmsen', 'Hart', 'Haver',
  'Heemskerk', 'Heerma', 'Heijden', 'Hendriks', 'Hengst', 'Hermans',
  'Heuvel', 'Hof', 'Hoek', 'Hoekstra', 'Hoffman', 'Hofman', 'Hofstede',
  'Holleman', 'Holt', 'Hoogeveen', 'Hoogendoorn', 'Horst', 'Houben',
  'Huisman', 'Huizen',
  'Jacobs', 'Jager', 'Jan', 'Jansen', 'Janssen', 'Janssens', 'Jong',
  'Jonge', 'Jongen', 'Jonker', 'Joosten',
  'Kamp', 'Kampen', 'Kant', 'Kappers', 'Karsten', 'Kerk', 'Kerkhof',
  'Keulen', 'Klein', 'Kleijn', 'Kling', 'Klok', 'Knaap', 'Knol',
  'Koek', 'Koeman', 'Kok', 'Koning', 'Kool', 'Koopman', 'Koopmans',
  'Koot', 'Korte', 'Koster', 'Kraai', 'Kramer', 'Kroon', 'Kuijper',
  'Kuijpers', 'Kuiper', 'Kuipers',
  'Laan', 'Laar', 'Laarhoven', 'Lam', 'Lange', 'Leemans', 'Leeuw', 'Leeuwen',
  'Linden', 'Lingen', 'Looij', 'Loon', 'Lucassen',
  'Maas', 'Maassen', 'Maat', 'Mans', 'Meer', 'Meijer', 'Meijers',
  'Meulen', 'Meyer', 'Molenaar', 'Mol', 'Molen', 'Mulder', 'Muller',
  'Nagelkerke', 'Nauta', 'Nieuwenhuis', 'Nijhof', 'Nijhuis', 'Nijland',
  'Nobel', 'Nooij', 'Noort', 'Norden',
  'Oerlemans', 'Oomen', 'Oord', 'Oorschot', 'Oort', 'Oosterhuis', 'Otten', 'Oudshoorn',
  'Pas', 'Peters', 'Petersen', 'Pieters', 'Pietersen', 'Plasman', 'Poel',
  'Pol', 'Polet', 'Post', 'Postma', 'Prins', 'Pronk',
  'Raad', 'Raven', 'Reijnen', 'Riet', 'Rijke', 'Rijn', 'Rijnders',
  'Rijswijk', 'Roelofs', 'Roos', 'Rosenberg', 'Ruiter', 'Rutten',
  'Schaaf', 'Schaap', 'Schenk', 'Schilder', 'Schipper', 'Schmid',
  'Schmidt', 'Schneider', 'Schoenmaker', 'Scholten', 'Schouten', 'Schreuder',
  'Schulte', 'Siebelink', 'Sloot', 'Sluiter', 'Smeets', 'Smid', 'Smit',
  'Smits', 'Snijder', 'Snijders', 'Steen', 'Steenbergen', 'Stolk',
  'Stout', 'Strijbos', 'Struijk', 'Stuij', 'Swart',
  'Terpstra', 'Timmerman', 'Timmermans', 'Toorn',
  'Vaart', 'Valk', 'Veenstra', 'Veld', 'Velde', 'Velden', 'Ven',
  'Verbeek', 'Verhoef', 'Verhoeven', 'Vermeer', 'Vermeulen', 'Verschoor',
  'Verschuren', 'Visser', 'Vliet', 'Vogel', 'Vonk', 'Voorn', 'Vos',
  'Vries', 'Vrij', 'Vugt', 'Vuuren',
  'Waal', 'Wagenaar', 'Wal', 'Wassink', 'Weerden', 'Weg', 'Wester', 'Westerhof',
  'Westerink', 'Westra', 'Willems', 'Willemsen', 'Wit', 'Wolff', 'Wolters',
  'Woud', 'Woude',
  'Zaal', 'Zanden', 'Zandstra', 'Zee', 'Zeeman', 'Zijl', 'Zijlstra',
  'Zoet', 'Zwaan', 'Zwart',
];

/**
 * Tussenvoegels die voorkomen in Nederlandse achternamen
 */
export const DUTCH_PREFIXES: string[] = [
  'de', 'den', 'der', 'des',
  "d'", // Italiaanse/Franse namen: d'Angelo, d'Souza
  'het', "'t",
  'van', 'van de', 'van den', 'van der', 'van het', "van 't",
  'in', 'in de', 'in den', "in 't",
  'op', 'op de', 'op den', 'op het', "op 't",
  'te', 'ten', 'ter',
  'tot',
  'uit', 'uit de', 'uit den', 'uit het', "uit 't",
  'aan', 'aan de', 'aan den', 'aan het', "aan 't",
  'bij', 'bij de', 'bij den', 'bij het', "bij 't",
  'onder', 'onder de', 'onder den', 'onder het',
  'over', 'over de', 'over den', 'over het',
  'voor', 'voor de', 'voor den', 'voor het',
  'El', 'el', // Arabische namen: El Amrani
  'Al', 'al', // Arabische namen: Al Bakri
];

/**
 * Aanspreekvormen die aangeven dat een naam volgt
 */
export const NAME_INDICATORS: string[] = [
  // Titels en aanspreekvormen
  'Dhr.', 'Dhr', 'Mevr.', 'Mevr', 'Mw.', 'Mw',
  'de heer', 'mevrouw', 'meneer',
  'Dr.', 'Dr', 'Prof.', 'Prof', 'Mr.', 'Mr', 'Ir.', 'Ir',
  'Ing.', 'Ing', 'Ds.', 'Ds',

  // Velden
  'Naam:', 'naam:', 'Name:', 'name:',
  'Geachte', 'Beste',
  'geb.', 'geboren',

  // Begroetingen (informeel en formeel)
  'Hoi', 'hoi', 'Dag', 'dag', 'Hey', 'hey', 'Hallo', 'hallo',
  'Hi', 'hi', 'Lieve', 'lieve', 'Groetjes', 'groetjes',
  'Groeten', 'groeten', 'Liefs', 'liefs',

  // Juridisch / administratief
  'namens', 'ondertekend door', 'ondertekend',
  't.a.v.', 'ter attentie van', 'T.a.v.',

  // Rollen (zorg en organisatie)
  'contactpersoon', 'Contactpersoon',
  'behandelaar', 'Behandelaar',
  'patiënt', 'Patiënt', 'patient', 'Patient',
  'cliënt', 'Cliënt', 'client', 'Client',
  'bewoner', 'Bewoner',
  'verzekerde', 'Verzekerde',
  'mantelzorger', 'Mantelzorger',
  'begeleider', 'Begeleider',
  'verpleegkundige', 'Verpleegkundige',
  'verzorgende', 'Verzorgende',
  'hulpverlener', 'Hulpverlener',
  'zorgverlener', 'Zorgverlener',
  'medewerker', 'Medewerker',
  'collega', 'Collega',
  'huisarts', 'Huisarts',
  'specialist', 'Specialist',
  'arts', 'Arts',
  'therapeut', 'Therapeut',
  'psycholoog', 'Psycholoog',
  'wijkverpleegkundige', 'Wijkverpleegkundige',
  'casemanager', 'Casemanager',

  // Relatie-aanduidingen
  'dhr.', 'mevr.',
  'partner van', 'echtgenoot van', 'echtgenote van',
  'zoon van', 'dochter van',
  'vader van', 'moeder van',
  'broer van', 'zus van',
];
